### ISSUE TITLE
Influxdb Clojar missing

### ISSUE THREAD

**Issue by miketwenty1** [sjl/metrics-clojure#113]
Seems that the Clojar for influxdb wrapper is missing.  I would greatly appreciate you adding this :) 
https://clojars.org/search?q=metrics-clojure-influxdb
As you can see from the link above there are no hits with the 2.7.0 version.

**Comment by miketwenty1** [comment]
https://twitter.com/michaelklishin/status/813876721996926980
As discussed.  Influxdb was added after 2.7.0 release and will be added in whenever 2.8.0 goes in. 
I was just a little confused. Thanks Michael!

**Comment by michaelklishin** [comment]
`2.8.0` is up on Clojars now.
