### ISSUE TITLE
Per-endpoint ring metrics

### ISSUE THREAD

**Issue by cddr** [sjl/metrics-clojure#119]
Seems like it would be useful to be able to record metrics for each endpoint in an app. In theory since it just wraps a handler, you could wrap each endpoint individually, but then you'd register the same metric twice. Would be nice if the "instrument-ring" function accepted a prefix that could be used to ensure each metric is uniquely named when wrapping multiple endpoints.

Does that make sense? I can come up with a PR if this sounds ok.

**Comment by michaelklishin** [comment]
@cddr sounds worth exploring. Thank you!
