### ISSUE TITLE
All return type hints should be fully-qualified

### ISSUE THREAD

**Issue by puredanger** [sjl/metrics-clojure#66]
If return type hints are not fully-qualified, they can require the returned class to be imported in the calling code, which may not even know about the underlying type hint. This is the simplest case where I can cause this to occur with the current code base:

```clojure
(require 'metrics.timers)
(.stop (metrics.timers/start (metrics.timers/timer "t")))
;; => CompilerException java.lang.IllegalArgumentException: Unable to resolve classname: Timer$Context
```

I realize this is a nonsensical example, however it can occur in real circumstances where it is impossible for the caller to fix. For example, when using metrics-clojure in tandem with core.async and wishing to wrap a timer around the body of a go block, you could do this:

```clojure
(require '[clojure.core.async :as async])
(require '[metrics.timers])

(def my-timer (metrics.timers/timer "t"))
(async/go
  (let [c (metrics.timers/start my-timer)]
    (+ 1 1)
    (metrics.timers/stop c)))

;;=> ExceptionInfo Class not found: Timer$Context
```

The error here is in relation to the non-qualified return type on the metrics.timers/start function. In this case, the place where the class would need to be imported to fix the error is inside a third-party, specifically clojure.tools.analyzer.jvm. So there is no practical way for a user to fix this. 

To fix, all return type hints in this library should be fully-qualified. 

Here is a comment from Rich Hickey about this behavior: http://dev.clojure.org/jira/browse/CLJ-1232?focusedCommentId=34819&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-34819
Regarding that ticket, I would like to be noisy about this problem when it is created rather than silent as it is now, but this is the current behavior.

Eastwood (https://github.com/jonase/eastwood) has a check for this problem to find it in static analysis under the https://github.com/jonase/eastwood#wrong-tag linter.

**Comment by michaelklishin** [comment]
Thank you, this is indeed something I've run into myself.

**Comment by puredanger** [comment]
Thanks!

**Comment by puredanger** [comment]
It seems like the pr creates an invalid type of ^clojure.core$long - that should just be ^long as it was. Also, the change does not fix a number of other cases I see browsing the code:

* metrics.core/new-registry - ^MetricRegistry
* metrics.timers/timer - ^Timer
* metrics.utils/snapshot - ^Snapshot
* metrics.reporters.console/reporter - ^ConsoleReporter
* metrics.reporters.csv/reporter - ^CsvReporter
* metrics.reporters.jmx/reporter - ^JmxReporter
* metrics.reporters.ganglia/reporter - ^GangliaReporter
* metrics.reporters.graphite/reporter - ^GraphiteReporter

**Comment by jwhitlark** [comment]
Sorry, I went off the :wrong-tags linter on eastwood.  I'll go back through it.

**Comment by jwhitlark** [comment]
I didn't see any that @puredanger didn't point out.  Let me know if there's anything I need to take a closer look at.

**Comment by michaelklishin** [comment]
@jwhitlark @puredanger this is in `2.5.0`.
