### ISSUE TITLE
Make `remove-metric` accepts a predicate

### ISSUE THREAD

**Issue by vincentbernat** [sjl/metrics-clojure#81]
Hey!

Would it be possible to make `remove-metric` accepts a predicate (or `remove-all-metrics`, or a new `remove-metrics`). The use case is I am registering metrics for various subsystems and it would be more convenient to remove all the metrics related to the given subsystem at once. I can easily identify them because they share the same group name.

**Comment by michaelklishin** [comment]
@vincentbernat `remove-metrics` that accepts a predicate sounds good. Feel free to look into a pull request.
