### ISSUE TITLE
Ability to retrieve a gauge by name

### ISSUE THREAD

**Issue by vincentbernat** [sjl/metrics-clojure#83]
Hi!

For all other types, it's possible to retrieve the metric by its name. For example `(meter reg ["alpha" "beta" "gamma"])` will retrieve the meter if it already exists. There is no such possibility for a gauge. Maybe adding a `gauge` method for that (which won't allow creation)?

**Comment by michaelklishin** [comment]
I don't think there's a particular reason for that.

**Comment by vincentbernat** [comment]
Do you mean we should be able to use `gauge-fn` to retrieve an existing gauge?

**Comment by michaelklishin** [comment]
@vincentbernat no, I mean that a function can be missing for no particular reason. Feel free to add it.
