### ISSUE TITLE
code still uses com.codahale.metrics package name not io.dropwizard.metrics

### ISSUE THREAD

**Issue by jeffmad** [sjl/metrics-clojure#90]
Maybe I am missing something, but if sjl/metrics-clojure is using 3.1 version of metrics now with the 2.6.0 release, then the package names should be  (:import [io.dropwizard.metrics MetricRegistry])  not (:import [com.codahale.metrics MetricsRegistry])

(ns metrics.core
  (:import [com.codahale.metrics MetricRegistry Metric]))

(def ^{:tag MetricRegistry :doc "Default registry used by public API functions when no explicit registry argument is given"}
  default-registry
  (MetricRegistry.))

(defn ^com.codahale.metrics.MetricRegistry new-registry
  []
  (MetricRegistry.))

https://github.com/dropwizard/metrics/blob/master/metrics-core/src/main/java/io/dropwizard/metrics/MetricRegistry.java

**Comment by michaelklishin** [comment]
@jeffmad please submit a pull request.

**Comment by jeffmad** [comment]
will do.

**Comment by michaelklishin** [comment]
@jeffmad actually, in v3.1.2, package names are still [com.codahale](https://github.com/dropwizard/metrics/blob/v3.1.2/metrics-core/src/main/java/com/codahale/metrics/MetricRegistry.java), so you are looking at master.

**Comment by jeffmad** [comment]
Michael, sorry for the confusion I caused.

**Comment by michaelklishin** [comment]
@jeffmad no worries, it's a good heads up for us: at some point we'll have to upgrade beyond `3.1.2` ;)
