### ISSUE TITLE
Update documentation on readthedocs

### ISSUE THREAD

**Issue by vincentbernat** [sjl/metrics-clojure#97]
Hey!

http://metrics-clojure.readthedocs.org/en/latest/ seems to be out-of-date (2.5.0-snapshot). Could you update it? Thanks!

**Comment by michaelklishin** [comment]
[This shows 2.6.1](http://metrics-clojure.readthedocs.org/en/latest/installation.html) for me. Generally the docs are updated shortly after pushing.

**Comment by vincentbernat** [comment]
Oh, I was misguided by the top bar saying 2.5.0-SNAPSHOT. I'll do a PR to grab the version from project.cljj.
